_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
                - 5
                - 49
                - 53
                - 55
                - 71
            "2":
                - 1
                - 5
                - 49
                - 53
                - 55
                - 71
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.10.12
            "5": 0.19.8
            "8":
                - 5
            "12": 0.19.8
            "13": linux-x86_64
DATAINFO:
    value:
        datadir: ./dataset/ETT-small/ETTh1.csv
DATASET:
    value:
        batch_size: 32
        datadir: ./dataset/ETT-small/
        dataname: ETTh1.csv
        del_feature: null
        drop_last: true
        label_len: 0
        num_workers: 0
        pin_memory: true
        pred_len: 336
        scaler: standard
        seq_len: 96
        shuffle: true
        split_rate:
            - 0.7
            - 0.1
            - 0.2
        time_embedding:
            - 0
            - m
        window_size: 96
DEFAULT:
    value:
        exp_name: forecasting_ETTh1_96_336
        seed: 42
LOSS:
    value:
        loss_name: ImageMSE
MODEL:
    value:
        modelname: PatchTST
MODELSETTING:
    value:
        activation: gelu
        affine: true
        batch_size: 32
        c_out: 7
        d_ff: 128
        d_layers: 1
        d_model: 16
        dec_in: 7
        decomposition: true
        dim_in: 7
        dropout: 0.3
        e_layers: 2
        embed: timeF
        enc_in: 7
        fc_dropout: 0.3
        freq: h
        head_dropout: 0
        individual: false
        kernel_size: 25
        label_len: 0
        moving_avg: 25
        n_heads: 8
        output_attention: false
        padding_patch: 0
        patch_len: 16
        pred_len: 336
        revin: true
        seq_len: 96
        stride: 8
        subtract_last: false
OPTIMIZER:
    value:
        lr: 0.0001
        opt_name: adamw
        params:
            weight_decay: 0.0005
RESULT:
    value:
        savedir: ./saved_model
TRAIN:
    value:
        batch_size: 64
        ckp_metric: MAE
        data_num: 0
        del_pt_file: true
        early_stopping_count: 5
        early_stopping_metric: MSE
        epoch: 10
        eval_epochs: 1
        fine_tuning_method: full
        grad_accum_steps: 1
        log_epochs: 1
        log_eval_iter: 100
        lradj: type1
        mixed_precision: "no"
        pre_training: false
        resume: null
        return_output: false
        wandb:
            entity: hankyeol
            exp_name: Autoformer_0
            iter: 50
            project_name: pretraining-TSF
            use: true
